# Docs for Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core backend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x'
  BACKEND_PROJECT: './backend/backend.csproj' # Path to your backend csproj
  AZURE_WEBAPP_NAME: 'my-own-supersimple-weather-app'
  PUBLISH_FOLDER: './publish'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build backend project
        run: dotnet build ${{ env.BACKEND_PROJECT }} --configuration Release

      - name: Publish backend project
        run: dotnet publish ${{ env.BACKEND_PROJECT }} -c Release -o ${{ env.PUBLISH_FOLDER }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ${{ env.PUBLISH_FOLDER }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required if using OIDC login
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_737AD74C2213402292E281AC06E82DD2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93512B23E2114B36909049BFD5CA264A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_835A84E9F7684B3394294333562F1D26 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.PUBLISH_FOLDER }}

